### ISSUE TITLE
工作流开始就完成了

### ISSUE THREAD

**Issue by Dou-Yu** [lc1415104/Abp.WorkflowCore#13]
我是先创建工作流设计,然后在创建业务后，通过这个工作流设计的ID和Version来开始启动工作流,但是有时候启用的工作流只走到第一个阶段就直接完成了，workflowexecutionpointers 也只有一条数据，就是StepName 为start_开头的步骤，下面的步骤就没有继续，请问您遇见过这个问题吗？

**Comment by mettoc** [comment]
没遇到过，您调试看呢

**Comment by Dou-Yu** [comment]
更新WorkflowCore 就可以了，谢谢
